/*====================================================================================================
Payer Performance Report
======================================================================================================
Purpose
  This report provides a Summarized view of payer performance within the healthcare system.
  It evaluates how different payers contribute to encounter activity, claim costs, and financial
  coverage.
Key Components
    1. Core Payer Attributes
       - Retrieves essential payer-level fields including:
         • Payer name
         • Payer address and location details
         • Encounter year
         • Associated encounter financial measures
    2. Aggregated Encounter Metrics
       - Computes summary metrics associated with each payer:
         • Total encounters 
         • Number of unique patients 
         • Total claim cost generated by payer-related encounters
         • Total payer coverage applied to those claims
    3. Operational and Financial KPIs
       - Calculates key performance indicators used to evaluate payer impact and financial
         coverage behavior:
         • Average length of stay (hours) for payer-related encounters
         • Average claim cost per encounter
         • Average payer coverage per encounter
    4. Payer Performance Benchmarking
       - Ranks payer total claim and coverage costs within each year to identify major contributors
         to healthcare utilization and highlight shifts in payer activity over time.
    5. Coverage Contribution Analysis
       - Calculates the percentage contibution by each payer to the
         • Overall total claim costs per year
         • Overall Payer coverage per year
         • Percentage of total claim costs covered
         providing insight into payer financial responsibility and coverage performance. 
========================================================================================================
*/
CREATE VIEW gold.report_payers AS
WITH Base_query AS (
--> 1) Base query: Retrives core columns from the tables
SELECT
    e.Patient_key,
    p.Gender,
    DATEDIFF(Year, p.Birth_date, GETDATE())                                               AS Age,
    e.Encounter_start_time,
    e.Encounter_end_time,
    YEAR( e.Encounter_start_time)                                                         AS Encounter_year,
    Month( e.Encounter_start_time)                                                        AS Encounter_month,
    DATEDIFF(Hour, e.Encounter_start_time, e.Encounter_end_time)                          AS Encounter_duration_hours,
    e.Total_claim_cost,
    e.Payer_coverage,
    py.Payer_name,
    py.City
FROM gold.fact_encounters e
LEFT JOIN gold.dim_patients p
ON e.Patient_key = p.Patient_key
LEFT JOIN gold.dim_payers py
ON e.Payer_key = py.Payer_key
WHERE e.Encounter_start_time IS NOT NULL

)
, Payer_aggregations AS (
SELECT
     Encounter_year,
     Payer_name,
     City,
     COUNT(*)                                                                              AS Total_encounters,
     COUNT(DISTINCT Patient_key)                                                           AS Unique_patients,
     SUM(Total_claim_cost)                                                                 AS Total_claim_cost,
     ROUND(CAST(AVG(Total_claim_cost)AS FLOAT), 2)                                         AS Avg_claim_cost,
     SUM(Payer_coverage)                                                                   AS Total_coverage,
     ROUND(CAST(AVG(Payer_coverage)AS FLOAT), 2)                                           AS Avg_coverage,
     ROUND(CAST(AVG(Encounter_duration_hours)AS FLOAT), 2)                                 AS Avg_length_of_stay
FROM Base_query
GROUP BY  Encounter_year, Payer_name, City
)
SELECT
     Encounter_year,
     Payer_name,
     City,
     Total_encounters,
     Unique_patients,
     Total_claim_cost,
     Avg_claim_cost,
     Total_coverage,
     Avg_coverage,
     Avg_length_of_stay,
     CONCAT(ROUND(CAST(
               CASE WHEN SUM(Total_claim_cost) OVER (PARTITION BY Encounter_year) = 0 THEN NULL
                    ELSE Total_claim_cost / SUM(Total_claim_cost) OVER (PARTITION BY Encounter_year) * 100
               END AS FLOAT), 2), '%')                                                     AS Percentage_of_total_claim_cost,
     CONCAT(ROUND(CAST(
              CASE WHEN SUM(Total_coverage) OVER (PARTITION BY Encounter_year) = 0 THEN NULL
                   ELSE Total_coverage / SUM(Total_coverage) OVER (PARTITION BY Encounter_year) * 100
              END AS FLOAT), 2), '%')                                                      AS Percentage_of_total_coverage,
     CONCAT(ROUND(CAST(Total_coverage AS FLOAT) 
               / NULLIF(Total_claim_cost,0) * 100, 2), '%') AS Total_claim_coverage_rate,
     DENSE_RANK() OVER (PARTITION BY Encounter_year ORDER BY  Total_claim_cost DESC)       AS Payer_revenue_rank,
     DENSE_RANK() OVER (PARTITION BY Encounter_year ORDER BY  Total_coverage DESC) as Payer_coverage_rank
    
FROM Payer_aggregations